const i18n = {
  nl: {
    'nav.about': 'Over mij',
    'nav.services': 'Services',
    'nav.experience': 'Ervaring',
    'nav.vision': 'Visie',
    'nav.contact': 'Contact',
    'hero.sub': 'Enterprise Architectuur &amp; IT Leiderschap',
    'hero.tagline': '<strong>Wanneer een extra perspectief helpt</strong>',
    'hero.desc': 'Senior ervaring in enterprise architectuur en IT-leiderschap — gedreven door innovatie, structuur, consistentie en teamspirit.',
    'hero.btn.services': 'Bekijk services',
    'hero.btn.contact': 'Neem contact op',
    'hero.stat1': 'Jaar ervaring',
    'hero.stat2val': 'Multinational',
    'hero.stat2': 'Bedrijven',
    'hero.stat3': '&amp; Leider',
    'about.label': 'Over Mij',
    'about.title': 'Ervaring die aanvult,<br>niet vervangt.',
    'about.p1': 'Mijn naam is Arnold Ruijter. Met meer dan 20 jaar ervaring in complexe enterprise-omgevingen is mijn doel om bij te dragen met mijn ervaring, perspectief en leiderschap waar en wanneer dat waarde toevoegt.',
    'about.p2': 'Ik streef ernaar bestaande capaciteiten te benutten en te omarmen door zoveel mogelijk vanuit dat standpunt verder te bouwen. Met andere woorden: versterk wat er al is en bied extra focus waar dat nodig is.',
    'about.quote': '"What you see is what you get" — Ik ben open, direct en transparant. Ik houd er geen halve waarheden op na, dus er is altijd duidelijkheid.',
    'about.p3': 'Ik begon mijn IT-loopbaan zonder bijzonder relevante studies — maar met veel nieuwsgierigheid. Van het ontleden van Excel-macro\'s, tot Visual Basic, tot enterprise-brede architectuur. In al die jaren ontwikkelde ik mijn eigen visie op de sleutelelementen van bedrijfs-IT.',
    'about.p4': 'Hoewel het grootste deel van mijn loopbaan op enterprise- of strategisch niveau heeft plaatsgevonden, ben ik ook thuis in domeinarchitectuur en opdrachten op elke schaal. Het niveau van de rol is minder belangrijk dan de kwaliteit van het resultaat.',
    'about.meta.avail': 'Beschikbaar voor interim- en adviesopdrachten',
    'about.ppp.title': 'Filosofie',
    'about.ppp.p1.title': 'Mensen',
    'about.ppp.p1.desc': 'IT kan niet slagen zonder de mensen die het gebruiken en bouwen. Ik investeer in het begrijpen van teams, het coachen van individuen en het opbouwen van vertrouwen — want resultaten volgen mensen.',
    'about.ppp.p2.title': 'Proces',
    'about.ppp.p2.desc': 'Elke organisatie werkt op een bepaalde manier, niet zonder reden. Het begrijpen van die processen — en ze respecteren terwijl je verandering mogelijk maakt, staat centraal bij elke transformatie.',
    'about.ppp.r.title': 'Praktijk',
    'about.ppp.r.desc': 'Pas dan kun je dieper ingaan op wat de doelen zijn, wat we willen verbeteren en hoe dat eruitziet in de praktijk. Niet als theoretisch model, maar als aanpak die daadwerkelijk landt — samen gevormd met de betrokken mensen.',
    'services.label': 'Wat ik bied',
    'services.title': 'Services',
    'services.desc': 'In mijn 30+ jaar ervaring — waaronder meer dan 20 jaar in grote ondernemingen met complexe processen en IT-landschappen — bied ik de volgende diensten aan:',
    'svc1.title': 'Enterprise &amp; Domeinarchitectuur',
    'svc1.desc': 'Analyseren van de organisatie, begrijpen van de bedrijfsprocessen en het IT-landschap en het ontwerpen van een solide weg vooruit — op enterprise-niveau of gericht op een specifiek domein.',
    'svc1.points': '<li>Analyseren van de organisatiestructuur vanuit IT-perspectief</li><li>Verzamelen van eisen bij business- en IT-stakeholders</li><li>Vastleggen van de huidige architectuur en ontwerpen van de toekomstige staat</li><li>Bouwen van de roadmap en bewaken van consistentie tijdens de transformatie</li><li>Domeinarchitectuur voor een specifiek IT-gebied of capability</li>',
    'svc2.title': 'IT Leiderschap',
    'svc2.desc': 'Bouwen van hoogpresterende IT-teams door mensen te begrijpen, sterktes te coachen en een omgeving van eigenaarschap en vertrouwen te creëren.',
    'svc2.points': '<li>Begrijpen van teamdynamiek, expertise en persoonlijke interesses</li><li>Coachen op sterktes en persoonlijk eigenaarschap</li><li>Begeleiden van communicatie binnen het team en richting stakeholders</li><li>Vertrouwenspersoon met een open-deurbeleid</li><li>Stimuleren van zelfsturing — teams die jou vertellen wat er speelt, niet andersom</li>',
    'svc3.title': 'Integratiearchitectuur',
    'svc3.desc': 'Ontwerpen van robuuste en schaalbare integratielandschappen voor Supply Chain, Finance, Product Master, Logistiek en meer.',
    'svc3.points': '<li>Analyseren van organisatie en IT-landschap op integratiegaten</li><li>Ontwerpen van integratiearchitectuur op basis van eisen</li><li>Naar behoefte toepassen van EDI-, EAI-, API- en middlewarepatronen</li><li>Ontwerpen of reviewen van mappingspecificaties en communicatieprotocollen</li><li>Behouden van architectuurconsistentie en documentatie</li>',
    'svc4.title': 'IT Strategie',
    'svc4.desc': 'Vertalen van zakelijke ambities naar een geprioriteerde, realistische IT-roadmap — afgestemd over teams en verankerd in de doelstellingen van de organisatie.',
    'svc4.points': '<li>Analyseren van kansen voor technologie om de business te laten groeien</li><li>Bepalen van het kritieke pad versus nice-to-have</li><li>Begeleiden van mensen door verandering met duidelijkheid over het "Waarom"</li><li>Samenbrengen van de visie van business en IT in één strategie</li><li>Verbinden van de technologie- en business-roadmap</li><li>Meedenken met management en ondersteunen van bedrijfsdoelstellingen</li>',
    'svc5.title': 'Advies &amp; Specialistische Opdrachten',
    'svc5.desc': 'Beschikbaar voor opdrachten buiten de traditionele enterprise-scope — van domeingerichte opdrachten tot cross-sectoraal advies, op de schaal die het best bij uw situatie past.',
    'svc5.points': '<li>Domeinarchitectuur binnen een specifiek systeem of IT-gebied</li><li>Cross-sectorale opdrachten — van retail en mode tot publieke sector en verder</li><li>Aanbestedingsondersteuning, leveranciersselectie en oplossingsassessment</li><li>Kleinere organisaties die baat hebben bij senior expertise op afroep</li><li>Managementadvies zonder langdurige commitment</li>',
    'exp.label': 'Loopbaan',
    'exp.title': 'Ervaring',
    'exp.desc': 'Enterprise Architect en IT-Director met meer dan 20 jaar ervaring in complexe, internationale retail- en modeomgevingen. Uitgebreide achtergrond in het definiëren van IT-strategie en enterprise-architectuur, het begeleiden van grootschalige digitale transformaties en het moderniseren van IT-landschappen — strategische visie gecombineerd met diepgaande technische expertise en een sterke organisatie- en stakeholderfocus.',
    'exp.badge': 'Huidig',
    'exp.s1.label': 'Huidig',
    'exp.s1.title': 'Arnold Ruijter IT',
    'exp.s2.label': 'Achtergrond',
    'exp.s2.title': 'Eerdere Werkervaring',
    'exp.assignment.label': 'Huidige Opdracht',
    'exp.pvh.period': 'Apr 2007 – Apr 2019 · 12 jaar',
    'exp.wf.role': 'Interim IT-manager <span class="tl-badge" data-i18n="exp.badge">Huidig</span>',
    'exp.wf.via': 'Via Arnold Ruijter IT · Semi-publieke sector',
    'exp.wf.points': '<li>Opzetten en organiseren van het IT-team — van losse eilanden naar één team, met transparantie in de werkzaamheden.</li><li>Implementeren en verbeteren van IT-processen en -procedures om support en bedrijfsbehoeften te beheersen.</li><li>Bouwen aan een sterke, toekomstbestendige basis.</li><li>IT-stakeholder voor een nieuw ERP-platform en de bijbehorende orkestratielaag.</li><li>Beheer van leveranciers en contracten.</li><li>Aansturing van auditactiviteiten.</li><li>Eindverantwoordelijk voor het AI-beleid van de organisatie, met een stapsgewijze uitrol van Microsoft 365 Copilot binnen de organisatie.</li>',
    'exp.1.role': 'Interim IT Consultant · Projectleider ESB Aanbesteding <span class="tl-badge" data-i18n="exp.badge">Huidig</span>',
    'exp.1.via': 'Via Arnold Ruijter IT · Publieke sector · Zuid-Holland',
    'exp.1.points': '<li>Leiding over het Europees aanbestedingsproces (EU aanbesteding) voor een Enterprise Service Bus namens GR IJsselgemeenten — een samenwerkingsverband van gemeenten in de regio Zuid-Holland.</li><li>Opstellen van kerndocumenten: Startnotitie, Aanbestedingsstrategie en Programma van Eisen (PvE).</li><li>Uitvoeren van marktconsultatie om eisen te valideren en het leverancierslandschap in kaart te brengen.</li><li>Beheren van de formele aanbestedingsprocedure via TenderNed, inclusief publicatie en Nota van Inlichtingen (vraag- en antwoordrondes met leveranciers).</li><li>Beoordelen van offertes op basis van gunningscriteria en opstellen van het Gunningsadvies.</li><li>Afstemming met juridische, IT- en managementstakeholders van de deelnemende gemeenten gedurende het gehele proces.</li>',
    'exp.own.label': 'Eigen Product',
    'exp.vinage.role': 'Oprichter &amp; Ontwikkelaar',
    'exp.vinage.via': 'Via Arnold Ruijter IT · Eigen product',
    'exp.vinage.points': '<li>Ontwerp, bouw en lancering van Vinage, een Progressive Web App (PWA) voor wijnkelderbeheer.</li><li>Volledig ontwikkeld met AI-assisted engineering (Claude Code, JavaScript): van architectuur tot productie.</li><li><a href="vinage.html">Lees de volledige casus →</a></li>',
    'exp.2.role': 'Eigenaar · Freelance IT Consultant <span class="tl-badge" data-i18n="exp.badge">Huidig</span>',
    'exp.2.points': '<li>Zelfstandig IT-adviesbureau met diensten op het gebied van enterprise-, integratie-, domein- en business-architectuur, IT-strategie, roadmaps en governance, en digitale &amp; ERP-transformatie.</li><li>Actief in meerdere sectoren — van retail en mode tot de publieke sector — op de schaal en het niveau dat de meeste waarde toevoegt.</li>',
    'exp.3.role': 'EMEA Tech Director',
    'exp.3.points': '<li>Verantwoordelijk voor Enterprise Architecture binnen EMEA en afstemming met het mondiale IT-governance.</li><li>Leidinggeven aan het IT-team verspreid over Europa (45 fte, ±30 externe consultants).</li><li>Mede-eigenaar van het BI Governance-programma: bevorderen van datakwaliteit, governance en datagedreven besluitvorming.</li><li>Leiden van Europese transformatie-initiatieven, waaronder onboarding van nieuwe landen en rationalisatie van IT-landschappen.</li><li>Bevorderen van standaardisatie, schaalbaarheid en beveiliging binnen EMEA.</li><li>Stakeholdermanagement met Europese leiders, mondiale teams in Boston en delivery-teams in Pune (India).</li>',
    'exp.4.role': 'Director IT Transformation',
    'exp.4.points': '<li>Verantwoordelijk voor het bepalen en uitvoeren van de algehele IT-strategie, Enterprise Architecture en de meerjarige roadmap.</li><li>Opbouwen van een brede IT-organisatie (5 → 25+ fte) over ERP, BI, security, eCom, infrastructuur en integratie.</li><li>Leiden van de enterprise-architectuur; principes, referentiearchitecturen en roadmap voor modernisering gedefinieerd.</li><li>Gemigreerd naar moderne cloud- en SaaS-platformen: OKTA, Boomi, Meraki, OneStream, Infor PLM, Akeneo PIM, AuditBoard.</li><li>60% minder supportincidenten door modernisering van netwerk en retailplatform.</li><li>ERP-migratie naar Infor CloudSuite voorbereid; omnichannel en integraties verbeterd.</li>',
    'exp.5.role': 'Eigenaar (Freelance)',
    'exp.5.points': '<li>IT- en enterprise-architectuuradvies voor retail- en modeklanten (onder andere Crocs, McGregor).</li><li>Ontwikkelen van doelarchitecturen en gestandaardiseerde bedrijfsprocessen.</li><li>Werkzaam op het gebied van EDI, datakwaliteit, middleware, eCom (Shopify) en ERP (SAP).</li><li>Coördinatie tussen Europese en Amerikaanse IT-teams, inclusief harmonisatie van data- en integratiestrategie.</li>',
    'exp.6.role': 'Sr. Manager ERP Development &amp; Integration',
    'exp.6.points': '<li>Leiding over SAP ERP- en integratieteams (AFS/FMS, HANA, PI/PO, Gateway, FIORI, Sterling).</li><li>Architectuur en governance rond ERP-migratie van AFS naar FMS.</li><li>Enterprise-architectuurprincipes gedefinieerd en doelarchitecturen gemodelleerd (inclusief ArchiMate).</li><li>OmniChannel-, API/Microservices-, PIM- en BI-capaciteiten versterkt.</li><li>Actieve rol bij SOX-compliance en afstemming met interne en externe auditors.</li><li>Transitie naar de Agile/DevOps-werkwijze.</li>',
    'exp.7.role': 'Manager ICT Integratie',
    'exp.7.points': '<li>Verantwoordelijk voor integratiearchitectuur voor meerdere merken (Calvin Klein, Tommy Hilfiger).</li><li>Verouderd integratielandschap gemoderniseerd; migratie van Sterling naar SAP PI.</li><li>Middleware-, EDI-, B2B- en EAI-oplossingen ontworpen voor supply chain, retail en finance.</li><li>Integraties gerealiseerd voor eCom, CRM, inkoop, forecasting en retail.</li>',
    'exp.8.role': 'Team Lead Integratie',
    'exp.8.points': '<li>Ondersteund bij integratie van Calvin Klein- en Tommy Hilfiger-systemen, inclusief migratie van AS400 naar SAP.</li><li>Ontwerp van middleware-interfaces en integratiestandaarden voor schaalbaarheid en efficiëntie.</li><li>A2A-interfaces gemigreerd van Sterling naar SAP PI; concessie- en consignatiemodellen ondersteund.</li>',
    'exp.9.role': 'Business Systems Analyst Integratie',
    'exp.9.points': '<li>SAP-interfaces ontwikkeld en onderhouden met Gentran Sterling; B2B- en EAI-integraties ondersteund.</li><li>eInvoicing-projecten en externe systeemintegraties geleid; processen gemodelleerd.</li><li>Interfaceontwikkeling voor retail-, bestel- en forecastingsystemen.</li>',
    'exp.10.role': 'Data Manager &amp; EDI Coördinator',
    'exp.10.points': '<li>Retailsysteemdata, artikelcreatie en leveranciersinformatie beheerd; winkeloperaties en rapportage ondersteund.</li><li>Bijgedragen aan EDI-implementatie en uitrol van het magazijnlogistieke systeem; medewerkers opgeleid en go-livesupport gecoördineerd.</li><li>Procesverbeteringen en documentatie opgeleverd voor de efficiëntie van de commerciële afdeling.</li>',
    'tech.label': 'Systeemlandschap',
    'tech.title': 'Technologie-ervaring',
    'tech.desc': 'Een breed scala aan platformen en systemen uit enterprise-omgevingen in retail, mode en logistiek.',
    'tech.g0': 'AI &amp; Ontwikkeling',
    'tech.g1': 'ERP-systemen',
    'tech.g2': 'Integratie &amp; Middleware',
    'tech.g3': 'BI &amp; Rapportage',
    'tech.g4': 'eCommerce &amp; Marktplaatsen',
    'tech.g5': 'Product &amp; Lifecycle',
    'tech.g6': 'Security &amp; Identity',
    'tech.g7': 'Supply Chain &amp; Logistiek',
    'tech.g8': 'HR &amp; Finance',
    'tech.g9': 'Planning &amp; Aanvulling',
    'tech.g10': 'Project &amp; Samenwerking',
    /* ---- Vinage ---- */
    'vin.label': 'Praktijkcasus · AI-Assisted Engineering',
    'vin.title': 'Vinage bouwen',
    'vin.desc': 'Vinage is een Progressive Web App voor wijnkelderbeheer. Het begon in februari 2026 als een gesprek met Claude, groeide uit tot iets wat ik dagelijks gebruik, en is inmiddels een product met betalende abonnees. iCulture riep het in juni uit tot App van de Maand. Ik heb het volledig zelf ontworpen, gebouwd en in productie gebracht met AI-assisted engineering — en die ervaring heeft veranderd hoe ik organisaties over AI adviseer.',
    'vin.cta.visit': 'Bekijk vinage.app',
    'vin.why.label': 'De aanleiding',
    'vin.why.title': 'Waarom ik het bouwde',
    'vin.why.p1': 'Twee dingen kwamen toevallig samen. Ik was al een tijd aan het experimenteren met Claude, en ik ergerde me al veel langer dat ik geen goede wijn-app kon vinden. In februari 2026 kwamen die twee samen in één gesprek, en daar begon Vinage.',
    'vin.why.quote': '"Hier was ik vroeger nooit aan begonnen. Niet omdat het idee nieuw was — maar omdat het bouwen buiten mijn bereik lag. Met AI niet meer."',
    'vin.why.p2': 'Dit was dus nooit een leerexperiment met een wijn-app als excuus, en ook geen product waarbij het leren bijvangst was. Het was vanaf de eerste dag allebei. De ergernis was echt, het plezier was echt, en de vraag wat er werkelijk bij komt kijken om een product te bouwen en draaiend te houden ook.',
    'vin.why.p3': 'Het begon voor mezelf. Na een paar maanden was het zo goed geworden dat ik het wilde delen, en op dat moment werd het een product met abonnementen — inclusief alles wat daarbij hoort: betalingen, accounts, privacy, support, zes talen. Dat bouwen én leren was minstens zo interessant als de app zelf.',
    'vin.why.p4': 'Bij elkaar komt het neer op vier à vijf maanden fulltime werk: als ZZP\'er zat ik eerst zonder klant en had dus tijd om aan Vinage te werken. Met vervolgens één klant werd dat een halve week, en uiteindelijk kwam het met een tweede klant aan op avonden en weekenden.',
    'vin.facts.title': 'In het kort',
    'vin.facts.f1.title': 'Alleen gebouwd',
    'vin.facts.f1.desc': 'Van eerste gesprek tot betalende abonnees, zonder ontwikkelteam.',
    'vin.facts.f2.title': 'In productie',
    'vin.facts.f2.desc': 'Een live app met echte gebruikers, echte betalingen en echte support — geen prototype.',
    'vin.facts.f3.title': 'Erkend',
    'vin.facts.f3.desc': 'Door iCulture uitgeroepen tot App van de Maand, juni 2026.',
    'vin.how.label': 'Onder de motorkap',
    'vin.how.title': 'Hoe het gebouwd is',
    'vin.how.desc': 'Vanilla JavaScript, geen framework, geen build-step. De app werkt zonder account en zonder verbinding; alleen de AI-etiketscan heeft verbinding nodig. Dat offline-first gedrag was vooraf geen eis — localStorage was simpelweg de makkelijkste start, en wat daaruit groeide bleek het waard om bewust vast te houden. Getest in vliegtuigmodus.',
    'vin.how.g1': 'App &amp; lokale opslag',
    'vin.how.g2': 'Cloud &amp; synchronisatie',
    'vin.how.g3': 'Product &amp; AI',
    'vin.how.g4': 'Uitlevering &amp; kwaliteit',
    'vin.how.gate': '"Niets gaat naar productie als ook maar één van zo\'n vierduizend asserts rood is. Die poort is de enige reden dat een eenmansproject zo snel kan bewegen zonder roekeloos te worden."',
    'vin.shots.label': 'De app',
    'vin.shots.title': 'Vinage in gebruik',
    'vin.shots.desc': 'Schermafbeeldingen uit mijn eigen kelder, op productie.',
    'vin.shots.s1': 'Beginscherm — de kelder in één oogopslag',
    'vin.shots.s2': 'Wijnrek — elke fles op zijn eigen plek',
    'vin.shots.s3': 'Scannen — etiketherkenning via de camera',
    'vin.shots.s4': 'Statistieken — kelderwaarde, rijping en gezondheid',
    'vin.learn.label': 'De echte opbrengst',
    'vin.learn.title': 'Wat ik heb geleerd',
    'vin.learn.desc': 'De app was nooit het resultaat. Deze lessen wel — en dat is wat ik nu meeneem in gesprekken over AI binnen IT-organisaties.',
    'vin.learn.c1.title': 'De cyclus sluit binnen één nacht',
    'vin.learn.c1.desc': 'Een productiefout die \'s avonds gemeld wordt, staat de volgende ochtend gefixt, getest en live. Dat is geen marginale winst — het verandert wát je überhaupt de moeite waard vindt om op te lossen.',
    'vin.learn.c1.points': '<li>Een gebruiker "kon niet scannen". In één avond gevonden: de app vroeg pas <em>ná</em> het maken van de foto om in te loggen. Gefixt, plus twee FAQ-vragen in zes talen, live.</li><li>Een gebruiker bleef hangen op een leeg laadscherm en niemand kon zien waarom. Foutlogging zonder persoonsgegevens, met offline-wachtrij en privacytekst in zes talen — één avond. Dat was vroeger een sprint.</li>',
    'vin.learn.c2.title': 'Overtuigend fout is het echte risico',
    'vin.learn.c2.desc': 'De fouten die mij het meest kostten waren nooit zichtbare fouten. Het waren antwoorden en tests die er volkomen juist uitzagen.',
    'vin.learn.c2.points': '<li>AI is goed in <em>wat</em> en slecht in <em>waar</em>: gevraagd om het etiket op een foto aan te wijzen, zat het kader er vijf van de vijf keer naast — ook na een betere instructie. De oplossing was niet het model overtuigen, maar de gebruiker het laatste woord geven met een kader dat hij zelf verschuift.</li><li>Vier keer in één maand stond een test op groen terwijl hij niets bewees. Hij controleerde niet het echte systeem, maar een namaakversie die zo was gebouwd dat er altijd het juiste antwoord uit kwam. De test bevestigde zichzelf. Groen betekent pas iets als je weet waar de test tegenaan praat.</li>',
    'vin.learn.c3.title': 'Snelheid vraagt om een rem die je zelf inbouwt',
    'vin.learn.c3.desc': 'Toen een wijziging een kwestie van minuten werd in plaats van dagen, accepteerde ik er op een dag meer dan ik kon overzien. De rem die vroeger vanzelf ontstond doordat werk nu eenmaal tijd kostte, moet je voortaan bewust inbouwen.',
    'vin.learn.c3.points': '<li>Op één dag voerde ik vier reeksen wijzigingen door. Twee daarvan repareerden problemen die de vorige ronde had veroorzaakt. En ergens onderweg had AI zelf bepaald hoe de app zich moest gedragen — een productkeuze die aan mij was. Ik heb die hele dag teruggedraaid.</li><li>Het script dat mijn werk naar productie brengt, deed alles behalve die ene stap waarvan ik aannam dat hij erin zat. Automatisering die je niet zelf hebt geschreven verdient dezelfde argwaan als code die je niet zelf hebt geschreven.</li>',
    'vin.learn.redo': '"Wat ik anders zou doen: ik had twee delen van de app als gescheiden werelden ontworpen. Gebruikers verwachtten dat ze in elkaar overliepen. Die aanname corrigeren kostte een complete ontwerpronde — de duurste fout van het project, en gemaakt vóór de eerste regel code."',
    'vin.next.label': 'Terug naar de praktijk',
    'vin.next.title': 'Waarom dit op enterprise-niveau uitmaakt',
    'vin.next.p1': 'Wat ik hier het vaakst over zeg: het helpt enorm om al gedegen IT-kennis te hebben als je met AI iets wilt bouwen. Ik begrijp wat er gebeurt, ook waar AI het beter doet dan ik zelf zou kunnen — en juist daardoor herken ik de dingen die ik nog niet wist. Iemand zonder die achtergrond heeft geen enkele manier om te zien wat AI wel en niet voor hem doet.',
    'vin.next.quote': '"Bouwen is goedkoop geworden. Weten wat je bouwt niet."',
    'vin.next.p2': 'Dat is architectenwerk, en dat is het deel dat niet goedkoper wordt: welke keuzes mag AI nemen, wat is de bron van waarheid, en wanneer stop je. Dat zijn dezelfde drie vragen, of je nu een wijnetiket omkadert of een beleidsnotitie opstelt.',
    'vin.next.p3': 'Ik ben op dit moment eindverantwoordelijk voor het AI-beleid bij een semi-publieke organisatie, inclusief een stapsgewijze uitrol van Microsoft 365 Copilot. Dat werk is merkbaar beter doordat ik zelf iets heb gebouwd. Beleid dat niet op eigen ervaring rust is een vendor-deck. En een AI die overtuigend fout is, is gevaarlijker dan een die zichtbaar faalt — dat is een governancevraagstuk lang voordat het een technisch vraagstuk is.',
    'vin.cta.contact': 'Neem contact op',
    'vin.cta.exp': 'Bekijk ervaring',
    'vision.label': 'Mijn Visie',
    'vision.title': 'Mensen, Proces &amp; Praktijk',
    'vision.p1': 'Bij IT-verandering verschuift de focus al snel naar oplossingen. Nieuwe systemen, nieuwe architectuur, nieuwe tooling. Begrijpelijk — maar het echte werk zit meestal ergens anders.',
    'vision.quote': '"Elke organisatie heeft haar eigen manier van werken — en meestal niet zonder reden. Als je de tijd niet neemt om dat te begrijpen, kun je iets ontwerpen dat er goed uitziet, maar dat niet <em>landt</em> in de praktijk."',
    'vision.p2': 'Het echte werk zit niet in de technologie, maar in hoe mensen werken — en waarom ze op die manier werken. Iets wat ik steeds opnieuw zie, in verschillende sectoren en organisaties van alle groottes.',
    'vision.p3': 'Dat is wat Mensen, Proces en Praktijk voor mij betekent. Eerst begrijpen hoe mensen denken, werken en wat hen drijft. Dan kijken hoe processen werkelijk verlopen — en waarom ze zo zijn gevormd. En pas daarna, samen, uitzoeken wat in de praktijk echt werkt.',
    'vision.v1.title': 'Transparantie boven Politiek',
    'vision.v1.desc': 'Ik zeg wat ik wel en niet kan. Ik houd er geen halve waarheden op na. Die duidelijkheid schept vertrouwen — en vertrouwen levert resultaten.',
    'vision.v2.title': 'Leiderschap door Vertrouwen',
    'vision.v2.desc': 'De eerste keer dat ik leidinggaf, probeerde ik mijn manager te kopiëren — en dat werkte niet. Ik leerde mezelf te zijn als leider: aandacht voor welzijn, beginnen met vertrouwen en vertrouwen op de bereidheid en capaciteiten van mensen.',
    'vision.v3.title': 'Jezelf Overbodig Maken',
    'vision.v3.desc': 'Het doel van goed leiderschap is je team in staat stellen eigen acties te ondernemen en beslissingen te nemen binnen afgesproken kaders. Een team dat jou niet nodig heeft om te vertellen wat ze moeten doen — dat is het doel.',
    'vision.v4.title': 'Hands-on Wanneer Nodig',
    'vision.v4.desc': 'Buiten strategische rollen geniet ik er oprecht van om dichter bij de details te komen. Nieuwsgierigheid en directe betrokkenheid zijn altijd de basis geweest van hoe ik leer en lever.',
    'cred.label': 'Kwalificaties',
    'cred.title': 'Opleiding &amp; Talen',
    'cred.edu.title': 'Opleiding &amp; Certificeringen',
    'cred.edu.3': '<strong>Post-Bachelor Bedrijfskundig Management</strong>NCOI',
    'cred.edu.4': '<strong>MBO &amp; MAVO Diploma\'s</strong>Basiskwalificaties',
    'cred.lang.title': 'Talen',
    'cred.lang.nl': 'Nederlands',
    'cred.lang.nl.level': 'Moedertaal',
    'cred.lang.en': 'Engels',
    'cred.lang.en.level': 'Vloeiend',
    'cred.lang.de': 'Duits',
    'cred.lang.de.level': 'Gemiddeld',
    'cred.lang.fr': 'Frans',
    'cred.lang.fr.level': 'Gemiddeld',
    'contact.label': 'Neem Contact Op',
    'contact.title': 'Laten we praten',
    'contact.desc': 'Ik hoor graag van u. Of u nu een specifieke opdracht in gedachten heeft of gewoon de mogelijkheden wilt verkennen, ik maak graag kennis.',
    'contact.loc.title': 'Locatie',
    'contact.loc.val': 'Castricum, Nederland',
    'contact.web.title': 'Website',
    'contact.co.title': 'Bedrijf',
    'contact.legal.title': 'Rechtsvorm',
    'contact.legal.val': 'Eenmanszaak',
    'contact.kvk.title': 'KVK (Kamer van Koophandel)',
    'contact.vat.title': 'BTW-nummer',
    'contact.kvk.note': 'Alle diensten worden geleverd onder toepasselijkheid van de algemene voorwaarden van Arnold Ruijter IT.<br>Land van vestiging: Nederland',
    'form.fname': 'Voornaam',
    'form.fname.ph': 'Uw voornaam',
    'form.lname': 'Achternaam',
    'form.lname.ph': 'Uw achternaam',
    'form.email': 'E-mail',
    'form.phone': 'Telefoon (optioneel)',
    'form.subject': 'Onderwerp',
    'form.subject.ph': 'Kies een onderwerp...',
    'form.opt.leadership': 'IT Leiderschap',
    'form.opt.strategy': 'IT Strategie',
    'form.opt.other': 'Overig',
    'form.message': 'Bericht',
    'form.message.ph': 'Vertel me over uw situatie of opdracht...',
    'form.submit': 'Verstuur bericht →',
    'footer.copy': '© 2026 Arnold Ruijter IT — Alle rechten voorbehouden',
    'footer.services': 'Services',
    'footer.experience': 'Ervaring',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacyverklaring',
    'explore.label': 'Verkennen',
    'explore.title': 'Dit vindt u op mijn website',
    'explore.desc': 'Van architectuur en leiderschap tot ervaring en visie — alles op één plek.',
    'explore.card1.title': 'Over mij',
    'explore.card1.desc': 'Wie ik ben, mijn filosofie en wat ik meeneem als consultant.',
    'explore.card2.title': 'Services',
    'explore.card2.desc': 'Enterprise architectuur, IT-leiderschap, integratie en strategisch advies.',
    'explore.card3.title': 'Ervaring',
    'explore.card3.desc': '20+ jaar in grote internationale ondernemingen, van PVH tot de publieke sector.',
    'explore.card4.title': 'Visie',
    'explore.card4.desc': 'Mijn kijk op mensen, proces en praktijk — en waarom dat het verschil maakt.',
    'explore.card5.title': 'Contact',
    'explore.card5.desc': 'Neem contact op voor een vrijblijvende kennismaking of een specifieke opdracht.',
    'explore.readmore': 'Lees meer →',
    'ppr.people': 'Mensen',
    'ppr.processes': 'Proces',
    'ppr.result': 'Praktijk',
  },
  en: {
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.experience': 'Experience',
    'nav.vision': 'Vision',
    'nav.contact': 'Contact',
    'hero.sub': 'Enterprise Architecture &amp; IT Leadership',
    'hero.tagline': '<strong>When an extra perspective helps</strong>',
    'hero.desc': 'Senior architecture &amp; leadership experience in enterprise IT — driven to achieve innovation, structure, consistency, and team spirit.',
    'hero.btn.services': 'View Services',
    'hero.btn.contact': 'Get in Touch',
    'hero.stat1': 'Years experience',
    'hero.stat2val': 'Global Scale',
    'hero.stat2': 'Companies',
    'hero.stat3': '&amp; Leader',
    'about.label': 'About Me',
    'about.title': 'Experience that<br>complements, not replaces.',
    'about.p1': 'My name is Arnold Ruijter. With over 20 years in complex enterprise environments, my goal is to add experience, perspective, and leadership where and when it adds value.',
    'about.p2': 'I aim to leverage &amp; embrace existing capability by building from that foundation as much as possible. In other words, strengthen what is already there and provide extra focus where it is needed.',
    'about.quote': '"What you see is what you get" — I am open, direct, and transparent. I do not maintain half-truths, so there is clarity at all times.',
    'about.p3': 'I started in IT without highly relevant studies — just a lot of curiosity. From dissecting Excel macros, to Visual Basic, to enterprise-wide architecture. In all those years, I developed my own vision on what I found are the key elements of business IT.',
    'about.p4': 'While much of my career has been at enterprise or strategic level, I am equally at home with domain architecture, cross-sector assignments, or engagements at any scale. The level of the role matters less than the quality of the outcome.',
    'about.meta.avail': 'Available for interim / advisory roles',
    'about.ppp.title': 'Philosophy',
    'about.ppp.p1.title': 'People',
    'about.ppp.p1.desc': 'IT cannot succeed without the people who use and build it. I invest in understanding teams, coaching individuals, and building trust — because results follow people.',
    'about.ppp.p2.title': 'Process',
    'about.ppp.p2.desc': 'Every organization does things a certain way, for a reason. Understanding those processes — and respecting them while enabling change — is at the heart of any transformation.',
    'about.ppp.r.title': 'Practice',
    'about.ppp.r.desc': 'Only then can you go deeper into what the goals are, what we want to improve and what that looks like in practice. Not as a theoretical model, but as an approach that actually lands — formed together with the people involved ',
    'services.label': 'What I Offer',
    'services.title': 'Services',
    'services.desc': 'In my 30+ years of experience — including more than 20 years in large enterprises with complex processes and IT landscapes — I provide the following services:',
    'svc1.title': 'Enterprise &amp; Domain Architecture',
    'svc1.desc': 'Analyse your organisation, understand business processes and the IT landscape, and design a coherent path forward — at enterprise level or scoped to a specific domain.',
    'svc1.points': '<li>Analyse organisation structure with a focus on IT</li><li>Gather requirements from business and IT stakeholders</li><li>Record current architecture and design the future state</li><li>Build the roadmap and safeguard consistency during transformation</li><li>TOGAF-certified approach to architecture governance</li><li>Domain architecture for a specific IT area or capability</li>',
    'svc2.title': 'IT Leadership',
    'svc2.desc': 'Build high-performing IT teams by understanding people, coaching strengths, and creating an environment of ownership and trust.',
    'svc2.points': '<li>Understand team dynamics, expertise, and interests</li><li>Coach on strengths and personal ownership</li><li>Guide communication within the team and with stakeholders</li><li>Be a person of trust with an open-door approach</li><li>Enable self-direction — teams that tell you, not the other way around</li>',
    'svc3.title': 'Integration Architecture',
    'svc3.desc': 'Design robust and scalable integration landscapes for Supply Chain, Finance, Product Master, Logistics, and more.',
    'svc3.points': '<li>Analyse organisation and IT landscape for integration gaps</li><li>Design integration architecture based on requirements</li><li>Apply EDI, EAI, API, and middleware patterns</li><li>Design or review mapping specifications and communication protocols</li><li>Maintain architecture consistency and documentation</li>',
    'svc4.title': 'IT Strategy',
    'svc4.desc': 'Translate business ambitions into a prioritised, realistic IT roadmap — aligned across teams and grounded in the organisation\'s goals.',
    'svc4.points': '<li>Analyse opportunities for technology to grow the business</li><li>Determine critical path vs. nice-to-have</li><li>Guide people through change with clarity on the "Why"</li><li>Align business and IT vision into a single coherent strategy</li><li>Bring the tech and business roadmap together</li><li>Brainstorm with management and support business targets</li>',
    'svc5.title': 'Advisory &amp; Specialist Roles',
    'svc5.desc': 'Available for engagements beyond the traditional enterprise scope — from domain-level assignments to cross-sector advisory, at whatever scale best fits your situation.',
    'svc5.points': '<li>Domain architecture within a specific system or IT area</li><li>Cross-sector engagements — from retail and fashion to public sector and beyond</li><li>Vendor selection, tendering support, and solution assessment</li><li>Smaller organisations that benefit from senior expertise on demand</li><li>Management advisory without a full-time or long-term commitment</li>',
    'exp.label': 'Career History',
    'exp.title': 'Experience',
    'exp.desc': 'Enterprise Architect and IT Executive with over 20 years of experience in complex, international retail and fashion environments. Extensive background in defining IT strategy and enterprise architecture, guiding large-scale digital transformations, and modernising IT landscapes — combining strategic vision with deep technical expertise and strong organisational and stakeholder awareness.',
    'exp.badge': 'Current',
    'exp.s1.label': 'Current',
    'exp.s1.title': 'Arnold Ruijter IT',
    'exp.s2.label': 'Background',
    'exp.s2.title': 'Previous Employment',
    'exp.assignment.label': 'Current Assignment',
    'exp.pvh.period': 'Apr 2007 – Apr 2019 · 12 years',
    'exp.wf.role': 'Interim IT Manager <span class="tl-badge" data-i18n="exp.badge">Current</span>',
    'exp.wf.via': 'Via Arnold Ruijter IT · Semi-public sector',
    'exp.wf.points': '<li>Setting up and organizing the IT team — from separate islands into one group, with transparency across its activities.</li><li>Implementing and improving IT processes and procedures to manage support and business needs.</li><li>Building a strong, future-proof foundation.</li><li>Acting as IT stakeholder for a new ERP platform and its orchestration layer.</li><li>Managing vendors and contracts.</li><li>Overseeing audit activities.</li><li>Accountable for the organisation\'s AI policy, with a phased rollout of Microsoft 365 Copilot across the organisation.</li>',
    'exp.1.role': 'Interim IT Consultant · Project Leader ESB Tender <span class="tl-badge" data-i18n="exp.badge">Current</span>',
    'exp.1.via': 'Via Arnold Ruijter IT · Public sector · South Holland',
    'exp.1.points': '<li>Leading the European public procurement process (EU aanbesteding) for an Enterprise Service Bus on behalf of GR IJsselgemeenten — a cooperation of municipalities in the South Holland region.</li><li>Authoring core procurement documents: Startnotitie, Aanbestedingsstrategie, and Programma van Eisen (PvE).</li><li>Conducting market consultation to validate requirements and understand the vendor landscape.</li><li>Managing the formal tender procedure via TenderNed, including publication and Nota van Inlichtingen (Q&amp;A rounds with suppliers).</li><li>Evaluating proposals against defined award criteria and preparing the Gunningsadvies (award recommendation).</li><li>Coordinating with legal, IT, and management stakeholders across the participating municipalities throughout the process.</li>',
    'exp.own.label': 'Own Product',
    'exp.vinage.role': 'Founder &amp; Developer',
    'exp.vinage.via': 'Via Arnold Ruijter IT · Own product',
    'exp.vinage.points': '<li>Designed, built and launched Vinage, a Progressive Web App (PWA) for wine cellar management.</li><li>Developed end-to-end with AI-assisted engineering (Claude Code, JavaScript): from architecture to production.</li><li><a href="vinage.html">Read the full case study →</a></li>',
    'exp.2.role': 'Owner · Freelance IT Consultant <span class="tl-badge" data-i18n="exp.badge">Current</span>',
    'exp.2.points': '<li>Independent IT consultancy providing enterprise, integration, domain and business architecture, IT strategy, roadmaps and governance, and digital &amp; ERP transformation.</li><li>Operating across sectors — from retail and fashion to public sector — at the scale and level that adds most value.</li>',
    'exp.3.role': 'EMEA Tech Director',
    'exp.3.points': '<li>Responsible for Enterprise Architecture within EMEA and alignment with global IT governance.</li><li>Leading the IT team spread across Europe (45 FTE, ±30 external consultants).</li><li>Co-owner of BI Governance program: promoting data quality, governance, and data-driven decision-making.</li><li>Leading European transformation initiatives, including onboarding new countries and rationalizing IT landscapes.</li><li>Promoting standardization, scalability, and security within EMEA.</li><li>Stakeholder management with European leadership, global teams in Boston, and delivery teams in Pune (India).</li>',
    'exp.4.role': 'Director IT Transformation',
    'exp.4.points': '<li>Responsible for defining and executing the overall IT strategy, Enterprise Architecture, and multi-year roadmap.</li><li>Built a broad IT organization (5 → 25+ FTE) across ERP, BI, security, eCom, infrastructure, and integration.</li><li>Led enterprise architecture; defined principles, reference architectures, and the roadmap for modernization.</li><li>Migrated to modern cloud and SaaS platforms: OKTA, Boomi, Meraki, OneStream, Infor PLM, Akeneo PIM, AuditBoard.</li><li>60% fewer support issues through network and retail platform modernization.</li><li>Prepared ERP migration to Infor CloudSuite; improved omnichannel and integrations.</li>',
    'exp.5.role': 'Owner (Freelance)',
    'exp.5.points': '<li>IT and enterprise architecture advice for retail and fashion clients (including Crocs, McGregor).</li><li>Development of target architectures and standardized business processes.</li><li>Working on EDI, data quality, middleware, eCom (Shopify), and ERP (SAP).</li><li>Coordination between European and US IT teams, including harmonisation of data and integration strategy.</li>',
    'exp.6.role': 'Sr. Manager ERP Development &amp; Integration',
    'exp.6.points': '<li>Led SAP ERP and integration teams (AFS/FMS, HANA, PI/PO, Gateway, FIORI, Sterling).</li><li>Architecture and governance around ERP migration from AFS to FMS.</li><li>Defined enterprise architecture principles and modelled target architectures (including ArchiMate).</li><li>Strengthened OmniChannel, API/Microservices, PIM, and BI capabilities.</li><li>Active role in SOX compliance and alignment with internal/external auditors.</li><li>Transition to Agile/DevOps ways of working.</li>',
    'exp.7.role': 'Manager ICT Integration',
    'exp.7.points': '<li>Responsible for integration architecture across multiple brands (Calvin Klein, Tommy Hilfiger).</li><li>Modernized legacy integration landscape; migrated from Sterling to SAP PI.</li><li>Designed middleware, EDI, B2B, and EAI solutions for supply chain, retail, and finance.</li><li>Realized integrations for eCom, CRM, procurement, forecasting, and retail.</li>',
    'exp.8.role': 'Team Lead Integration',
    'exp.8.points': '<li>Supported integration of Calvin Klein and Tommy Hilfiger systems, including migration from AS400 to SAP.</li><li>Design of middleware interfaces and integration standards for scalability and efficiency.</li><li>Migrated A2A interfaces from Sterling to SAP PI; supported concession and consignment models.</li>',
    'exp.9.role': 'Business Systems Analyst Integration',
    'exp.9.points': '<li>Developed and maintained SAP interfaces using Gentran Sterling; supported B2B and EAI integrations.</li><li>Led eInvoicing projects and external system integrations; modeled processes.</li><li>Interface development for retail, order, and forecasting systems.</li>',
    'exp.10.role': 'Data Manager &amp; EDI Coordinator',
    'exp.10.points': '<li>Managed retail system data, article creation, and supplier information; supported store operations and reporting.</li><li>Contributed to EDI implementation and warehouse logistics system rollout; trained staff and coordinated go-live support.</li><li>Delivered process improvements and documentation for commercial department efficiency.</li>',
    'tech.label': 'System Landscape',
    'tech.title': 'Technology Experience',
    'tech.desc': 'A broad range of platforms and systems encountered across enterprise environments in retail, fashion, and logistics.',
    'tech.g0': 'AI &amp; Development',
    'tech.g1': 'ERP Systems',
    'tech.g2': 'Integration &amp; Middleware',
    'tech.g3': 'BI &amp; Reporting',
    'tech.g4': 'eCommerce &amp; Marketplaces',
    'tech.g5': 'Product &amp; Lifecycle',
    'tech.g6': 'Security &amp; Identity',
    'tech.g7': 'Supply Chain &amp; Logistics',
    'tech.g8': 'HR &amp; Finance',
    'tech.g9': 'Planning &amp; Replenishment',
    'tech.g10': 'Project &amp; Collaboration',
    /* ---- Vinage ---- */
    'vin.label': 'Case Study · AI-Assisted Engineering',
    'vin.title': 'Building Vinage',
    'vin.desc': 'Vinage is a Progressive Web App for wine cellar management. It began in February 2026 as a conversation with Claude, grew into something I used every day, and is now a product with paying subscribers. iCulture named it App of the Month in June. I designed, built and shipped all of it myself, with AI-assisted engineering — and that experience has changed how I advise organisations about AI.',
    'vin.cta.visit': 'Visit vinage.app',
    'vin.why.label': 'The Origin',
    'vin.why.title': 'Why I Built It',
    'vin.why.p1': 'Two things happened to coincide. I had been experimenting with Claude for a while, and I had been irritated for far longer that I could not find a decent wine app. In February 2026 those two met in a single conversation, and Vinage started.',
    'vin.why.quote': '"I would never have started this before. Not because the idea was new — because building it was out of reach. With AI it was not."',
    'vin.why.p2': 'So this was never a learning exercise with a wine app as its excuse, nor a product where the learning was a by-product. It was both, from the first day. The irritation was real, the enjoyment was real, and the question of what it actually takes to build and run a product was real too.',
    'vin.why.p3': 'It began as something for myself. After a few months it had become good enough that I wanted to share it, and at that point it turned into a product with subscriptions — which brought along everything that comes with one: payments, accounts, privacy, support, six languages. Building that, and learning it, was every bit as interesting as the app itself.',
    'vin.why.p4': 'All in, it amounts to four to five months of full-time work. As a freelancer I was between clients at first, which gave me the time to work on Vinage. With one client after that it became half a week, and once a second client came along it turned into evenings and weekends.',
    'vin.facts.title': 'At a Glance',
    'vin.facts.f1.title': 'Built solo',
    'vin.facts.f1.desc': 'From first conversation to paying subscribers, without a development team.',
    'vin.facts.f2.title': 'In production',
    'vin.facts.f2.desc': 'A live app with real users, real payments and real support — not a prototype.',
    'vin.facts.f3.title': 'Recognised',
    'vin.facts.f3.desc': 'Named App of the Month by iCulture in June 2026.',
    'vin.how.label': 'Under the Hood',
    'vin.how.title': 'How It Is Built',
    'vin.how.desc': 'Vanilla JavaScript, no framework, no build step. The app works without an account and without a connection; only the AI label scan needs one. That offline-first behaviour was not a requirement up front — local storage was simply the simplest way to start, and what grew out of it turned out to be worth keeping deliberately. Tested in aeroplane mode.',
    'vin.how.g1': 'App &amp; Local Storage',
    'vin.how.g2': 'Cloud &amp; Sync',
    'vin.how.g3': 'Product &amp; AI',
    'vin.how.g4': 'Delivery &amp; Quality',
    'vin.how.gate': '"Nothing reaches production if a single one of roughly four thousand assertions is red. That gate is the only reason a one-person project can move this fast without becoming reckless."',
    'vin.shots.label': 'The App',
    'vin.shots.title': 'Vinage in Use',
    'vin.shots.desc': 'Screenshots from my own cellar, on production.',
    'vin.shots.s1': 'Home — the cellar at a glance',
    'vin.shots.s2': 'Rack — every bottle in its own position',
    'vin.shots.s3': 'Scan — label recognition through the camera',
    'vin.shots.s4': 'Statistics — cellar value, maturity and health',
    'vin.learn.label': 'The Real Output',
    'vin.learn.title': 'What I Learned',
    'vin.learn.desc': 'The app was never the deliverable. These lessons were — and they are what I now bring into conversations about AI inside IT organisations.',
    'vin.learn.c1.title': 'The loop closes overnight',
    'vin.learn.c1.desc': 'A production issue reported in the evening is fixed, tested and live the next morning. That is not a marginal gain — it changes what is worth fixing at all.',
    'vin.learn.c1.points': '<li>A user "could not scan". Found in one evening: the app only asked them to sign in <em>after</em> taking the photo. Fixed, plus two FAQ entries in six languages, live.</li><li>A user was stuck on an empty loading screen and no one could see why. Error logging without personal data, with an offline queue and a privacy notice in six languages — one evening. That used to be a sprint.</li>',
    'vin.learn.c2.title': 'Confidently wrong is the real risk',
    'vin.learn.c2.desc': 'The failures that cost me most were never visible failures. They were answers and tests that looked entirely right.',
    'vin.learn.c2.points': '<li>AI is good at <em>what</em> and poor at <em>where</em>: asked to point out the label in a photo, the frame was wrong five times out of five — better instructions included. The fix was not to convince the model, but to give the user the last word with a frame they move themselves.</li><li>Four times in one month a test was green while proving nothing. It was not checking the real system but a stand-in built so that the right answer always came out. The test was confirming itself. Green only means something once you know what the test is talking to.</li>',
    'vin.learn.c3.title': 'Speed needs a brake you build yourself',
    'vin.learn.c3.desc': 'Once a change took minutes rather than days, I accepted more of them in a day than I could keep track of. The brake that used to come free — because work simply took time — now has to be built in on purpose.',
    'vin.learn.c3.points': '<li>In a single day I pushed through four rounds of changes. Two of them repaired problems the previous round had caused. And somewhere along the way AI had decided by itself how the app should behave — a product choice that was mine to make. I reverted the entire day.</li><li>The script that takes my work to production did everything except the one step I had assumed was in it. Automation you did not write yourself deserves the same suspicion as code you did not write yourself.</li>',
    'vin.learn.redo': '"What I would do differently: I designed two parts of the app as separate worlds. Users expected them to flow into one another. Correcting that assumption cost a full redesign round — the most expensive mistake of the project, and it was made before the first line of code."',
    'vin.next.label': 'Back to Practice',
    'vin.next.title': 'Why This Matters at Enterprise Level',
    'vin.next.p1': 'The thing I say most often about this: it helps enormously to already have solid IT knowledge when you want to build something with AI. I understand what is happening, even where AI does it better than I could — and that is exactly what lets me recognise the things I did not yet know. Someone without that background has no way of telling what AI is and is not doing on their behalf.',
    'vin.next.quote': '"Building has become cheap. Knowing what you are building has not."',
    'vin.next.p2': 'That is architecture work, and it is the part that does not get cheaper: which decisions may AI make, what is the source of truth, and when do you stop. Those are the same three questions whether you are framing a wine label or drafting a policy note.',
    'vin.next.p3': 'I am currently accountable for the AI policy at a semi-public organisation, including a phased rollout of Microsoft 365 Copilot. That work is markedly better for having built something myself. Policy that does not rest on first-hand experience is a vendor deck. And an AI that is convincingly wrong is more dangerous than one that visibly fails — which is a governance problem long before it is a technical one.',
    'vin.cta.contact': 'Get in Touch',
    'vin.cta.exp': 'View Experience',
    'vision.label': 'My Vision',
    'vision.title': 'People, Process &amp; Practice',
    'vision.p1': 'When organisations talk about IT change, the focus quickly shifts to solutions. New systems, new architecture, new tooling. Understandable — but the real work usually sits somewhere else.',
    'vision.quote': '"Every organisation has its own way of doing things — usually not without reason. If you don\'t take the time to understand that, you can design something that looks right, but doesn\'t <em>land</em> in practice."',
    'vision.p2': 'The real work doesn\'t sit in the technology, but in how people work — and why they work that way. Something I keep noticing, across industries and organisations of all sizes.',
    'vision.p3': 'That is what People, Process and Practice means to me. First understanding how people think, work, and what drives them. Then looking at how processes actually flow — and why they are shaped the way they are. And only then figuring out, together, what really works in practice.',
    'vision.v1.title': 'Transparency Over Politics',
    'vision.v1.desc': 'I say what I can and cannot do. I don\'t maintain "bent truths." That clarity creates trust — and trust creates results.',
    'vision.v2.title': 'Leadership Through Trust',
    'vision.v2.desc': 'The first time I led people, I tried to copy my manager — and it didn\'t work. I learned to lead as myself: caring for wellbeing, starting with trust, and relying on people\'s willingness and capabilities.',
    'vision.v3.title': 'Making Yourself Redundant',
    'vision.v3.desc': 'The goal of good leadership is to enable your team to set their own actions and make decisions within agreed boundaries. A team that doesn\'t need you telling them what to do — that\'s the target.',
    'vision.v4.title': 'Hands-on When Needed',
    'vision.v4.desc': 'Beyond strategic roles, I genuinely enjoy getting closer to the detail. Curiosity and hands-on involvement have always been at the root of how I learn and deliver.',
    'cred.label': 'Qualifications',
    'cred.title': 'Education &amp; Languages',
    'cred.edu.title': 'Education &amp; Certifications',
    'cred.edu.3': '<strong>Post-Bachelor Business Management</strong>NCOI',
    'cred.edu.4': '<strong>MBO &amp; MAVO Diplomas</strong>Foundation qualifications',
    'cred.lang.title': 'Languages',
    'cred.lang.nl': 'Dutch',
    'cred.lang.nl.level': 'Native',
    'cred.lang.en': 'English',
    'cred.lang.en.level': 'Fluent',
    'cred.lang.de': 'German',
    'cred.lang.de.level': 'Average',
    'cred.lang.fr': 'French',
    'cred.lang.fr.level': 'Average',
    'contact.label': 'Get In Touch',
    'contact.title': 'Let\'s talk',
    'contact.desc': 'Looking forward to hearing from you. Whether you have a specific assignment in mind or just want to explore possibilities, I\'m happy to connect.',
    'contact.loc.title': 'Location',
    'contact.loc.val': 'Castricum, The Netherlands',
    'contact.web.title': 'Website',
    'contact.co.title': 'Company',
    'contact.legal.title': 'Legal form',
    'contact.legal.val': 'One-man business',
    'contact.kvk.title': 'KVK (Chamber of Commerce)',
    'contact.vat.title': 'VAT number',
    'contact.kvk.note': 'All services are provided under the applicability of the general terms and conditions of Arnold Ruijter IT.<br>Country of establishment: The Netherlands',
    'form.fname': 'First Name',
    'form.fname.ph': 'Your first name',
    'form.lname': 'Last Name',
    'form.lname.ph': 'Your last name',
    'form.email': 'Email',
    'form.phone': 'Phone (optional)',
    'form.subject': 'Subject',
    'form.subject.ph': 'Select a topic...',
    'form.opt.leadership': 'IT Leadership',
    'form.opt.strategy': 'IT Strategy',
    'form.opt.other': 'Other',
    'form.message': 'Message',
    'form.message.ph': 'Tell me about your situation or assignment...',
    'form.submit': 'Send Message →',
    'footer.copy': '© 2026 Arnold Ruijter IT — All rights reserved',
    'footer.services': 'Services',
    'footer.experience': 'Experience',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'explore.label': 'Explore',
    'explore.title': 'What you can find on my website',
    'explore.desc': 'From architecture and leadership to experience and vision — all in one place.',
    'explore.card1.title': 'About Me',
    'explore.card1.desc': 'Who I am, my philosophy, and what I bring as a consultant.',
    'explore.card2.title': 'Services',
    'explore.card2.desc': 'Enterprise architecture, IT leadership, integration, and strategic advisory.',
    'explore.card3.title': 'Experience',
    'explore.card3.desc': '20+ years across large international enterprises, from PVH to the public sector.',
    'explore.card4.title': 'Vision',
    'explore.card4.desc': 'My perspective on people, process, and practice — and why it makes the difference.',
    'explore.card5.title': 'Contact',
    'explore.card5.desc': 'Reach out for an exploratory conversation or a specific assignment.',
    'explore.readmore': 'Read more →',
    'ppr.people': 'People',
    'ppr.processes': 'Process',
    'ppr.result': 'Practice',
  }
};

let currentLang = localStorage.getItem('arit-lang') || 'nl';

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('arit-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang] && i18n[lang][key] !== undefined) el.innerHTML = i18n[lang][key];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (i18n[lang] && i18n[lang][key] !== undefined) el.placeholder = i18n[lang][key];
  });
  document.getElementById('btn-nl').classList.toggle('active', lang === 'nl');
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  const cookieText = document.getElementById('cookieText');
  if (cookieText) {
    cookieText.innerHTML = lang === 'nl'
      ? 'Deze website gebruikt functionele cookies en lokale opslag voor taalvoorkeur. Via het contactformulier worden persoonsgegevens verwerkt. Lees onze <a href="privacy.html">privacyverklaring</a>.'
      : 'This website uses functional cookies and local storage for language preferences. Personal data is processed via the contact form. Read our <a href="privacy.html">privacy policy</a>.';
    document.getElementById('cookieAccept').textContent = lang === 'nl' ? 'Accepteren' : 'Accept';
  }
}

function acceptCookies() {
  localStorage.setItem('arit-cookies', 'accepted');
  document.getElementById('cookieBar').style.display = 'none';
}

function initCookieBar() {
  if (!localStorage.getItem('arit-cookies')) {
    document.getElementById('cookieBar').style.display = 'flex';
  }
}

function toggleMenu() {
  const navLinks = document.getElementById('navLinks');
  navLinks.classList.toggle('open');
}

window.addEventListener('scroll', () => {
  const navbar = document.getElementById('navbar');
  if (window.scrollY > 10) {
    navbar.classList.add('scrolled');
  } else {
    navbar.classList.remove('scrolled');
  }
});

document.querySelectorAll('.nav-links a').forEach(link => {
  link.addEventListener('click', () => {
    document.getElementById('navLinks').classList.remove('open');
  });
});

const observer = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
    }
  });
}, { threshold: 0.1 });

document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.fade-in').forEach(el => observer.observe(el));
});
